/**
 * Colorado-only gazetteer for the copilot's `geocode` tool.
 *
 * ⚠️ COLORADO ONLY, DELIBERATELY. This app carries Colorado data and nothing else, so a place
 * outside the state is a question the extract cannot answer. Returning a point anyway would put
 * a marker where there is no data and read as "no risk here", which is the opposite of the
 * truth. Unknown places are REJECTED with the list of what is known, not approximated.
 *
 * Coordinates are city centres (the US Census place centroid, rounded to 4 decimals, roughly
 * 10 m), plus a few landmarks people actually ask about. "downtown <city>" resolves to the
 * city centre, which is what the phrase means at a 10-mile radius.
 *
 * The real fix for free-form places is an Overture places extract queried through the same
 * engine. This list exists so v1 can answer the questions people actually ask without that.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else (root.CoRiskQuery = root.CoRiskQuery || {}).gazetteer = factory();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  /**
   * ⚠️ EVERY LOOKUP USES has(), NEVER A BARE `PLACES[key]`.
   *
   * A plain object inherits `constructor`, `__proto__` and friends from Object.prototype, so
   * `PLACES["constructor"]` is truthy and the lookup "succeeds" with a value that is not a
   * place. geocode("constructor") returned `{ok:true, center:{}}`: the tool told the copilot the
   * place resolved and handed it an empty centre. A confident wrong answer, which is exactly
   * what this file's unknown-place rejection exists to prevent.
   *
   * Only lower-cased keys reach here (normalize() lower-cases), which is why `toString` and
   * `hasOwnProperty` happened not to collide while `constructor` and `__proto__` did. That is
   * luck, not a design, so the guard is on the lookup rather than on the spelling.
   */
  function has(key) { return Object.prototype.hasOwnProperty.call(PLACES, key); }

  // San Diego County: incorporated cities and unincorporated communities from the app's
  // places.json (Overture divisions), plus landmarks people name. Generated by
  // part2_map_app/data/build_gazetteer.py; edit that, not this list.
  var PLACES = {
    /* GAZETTEER:BEGIN */
    "4s ranch": [-117.1133, 33.0188],
    "agra": [-117.476, 33.3717],
    "alpine": [-116.7712, 32.8325],
    "balboa park": [-117.1466, 32.7341],
    "ballena": [-116.7685, 33.0679],
    "bankhead springs": [-116.2437, 32.6385],
    "banner": [-116.5315, 33.0768],
    "barona": [-116.8628, 32.9359],
    "barrett": [-116.4363, 32.6282],
    "barrett junction": [-116.7027, 32.6424],
    "bear valley": [-117.0478, 33.0898],
    "beulah picnic ground": [-116.5307, 32.8484],
    "big ewiiaapaayp": [-116.3261, 32.8378],
    "blossom valley": [-116.868, 32.8632],
    "bonita": [-117.0232, 32.6658],
    "bonsall": [-117.2327, 33.2937],
    "borrego springs": [-116.3794, 33.2601],
    "boulder oaks": [-116.8382, 32.8931],
    "boulevard": [-116.2727, 32.6498],
    "buena creek": [-117.2079, 33.1767],
    "calexico lodge": [-116.2801, 32.6682],
    "cameron corners": [-116.478, 32.6402],
    "campo": [-116.465, 32.6099],
    "canebrake": [-116.2522, 32.9068],
    "canyon city": [-116.5316, 32.5995],
    "carlsbad": [-117.2874, 33.1233],
    "casa de oro": [-116.994, 32.746],
    "chihuahua valley": [-116.6656, 33.3745],
    "chula vista": [-117.0272, 32.6276],
    "ch\u00e9vnimay": [-117.2399, 33.2453],
    "citrus valley": [-117.0337, 33.108],
    "cleveland national forest": [-116.67, 32.88],
    "clover flat": [-116.4213, 32.6522],
    "cohanga": [-116.8043, 33.2725],
    "corenga": [-116.8598, 33.2721],
    "coronado": [-117.1802, 32.6919],
    "crest": [-116.8732, 32.8171],
    "cupa": [-116.5913, 33.2636],
    "cuyamaca": [-116.583, 32.95],
    "de luz": [-117.3246, 33.4456],
    "de luz heights": [-117.2717, 33.4335],
    "dehesa": [-116.8492, 32.7859],
    "del cerro": [-117.07, 32.788],
    "del dios": [-117.1206, 33.0701],
    "del mar": [-117.263, 32.9596],
    "descanso": [-116.6082, 32.8574],
    "descanso junction": [-116.6091, 32.8424],
    "desert lodge": [-116.3306, 33.2053],
    "downtown san diego": [-117.1625, 32.7157],
    "dulzura": [-116.7761, 32.659],
    "eagles nest": [-116.5454, 33.3443],
    "eden valley": [-117.13, 33.1164],
    "el apajo": [-117.2027, 33.0004],
    "el cajon": [-116.9541, 32.7973],
    "elfin forest": [-117.1756, 33.0805],
    "ellykwanan": [-116.667, 33.1546],
    "encinitas": [-117.2701, 33.0504],
    "engineer springs": [-116.7469, 32.6353],
    "escondido": [-117.0771, 33.1281],
    "eucalyptus hills": [-116.9436, 32.8765],
    "fairbanks ranch": [-117.1826, 32.9895],
    "fallbrook": [-117.2441, 33.3781],
    "felicita park": [-117.0868, 33.082],
    "fernbrook": [-116.9084, 32.9675],
    "flinn springs": [-116.8478, 32.8541],
    "foster": [-116.9233, 32.8993],
    "four corners": [-116.7924, 32.9797],
    "funner": [-116.9727, 33.2468],
    "gopher canyon": [-117.2075, 33.2466],
    "guatay": [-116.5642, 32.8597],
    "hacienda del florasol": [-116.4959, 32.6085],
    "harbison canyon": [-116.8202, 32.8234],
    "harmony grove": [-117.1328, 33.1025],
    "harrison park": [-116.5779, 33.016],
    "hidden meadows": [-117.1049, 33.224],
    "holcomb village": [-116.7305, 33.3503],
    "homelands": [-116.9684, 32.7439],
    "hulburd grove": [-116.6239, 32.8638],
    "imperial beach": [-117.1161, 32.5788],
    "irvings crest": [-116.901, 32.9888],
    "jacumba hot springs": [-116.1819, 32.6303],
    "jamul": [-116.875, 32.7227],
    "jamul indian village": [-116.8634, 32.6779],
    "japatul": [-116.6569, 32.7899],
    "japatul highlands": [-116.6377, 32.8137],
    "jesmond dene": [-117.1024, 33.1827],
    "jofegan": [-117.3264, 33.3152],
    "julian": [-116.6041, 33.0778],
    "kentwood-in-the-pines": [-116.5782, 33.0679],
    "kuhwaat": [-116.7428, 32.7775],
    "kumehall": [-116.7492, 33.167],
    "k\u00fauki": [-116.9022, 33.2946],
    "la jolla": [-117.2713, 32.8328],
    "la jolla amago": [-116.8581, 33.2913],
    "la mesa": [-117.0233, 32.7699],
    "la posta": [-116.4105, 32.716],
    "la presa": [-117.0034, 32.711],
    "laguna junction": [-116.5406, 32.7781],
    "lake hodges": [-117.1045, 33.0821],
    "lake morena village": [-116.5048, 32.6764],
    "lake san marcos": [-117.2094, 33.1217],
    "lake wohlford": [-116.9706, 33.1927],
    "lakeside": [-116.914, 32.8533],
    "las flores": [-117.4019, 33.2519],
    "lau hala canyon": [-117.2609, 33.1799],
    "lawrence welk resort village": [-117.1401, 33.2351],
    "lehner valley": [-117.0825, 33.1651],
    "lemon grove": [-117.0342, 32.7321],
    "lilac": [-117.0722, 33.2791],
    "lincoln acres": [-117.0918, 32.6412],
    "little borrego": [-116.1242, 33.1032],
    "little ewiiaapaayp": [-116.7311, 32.8306],
    "live oak springs": [-116.3284, 32.6896],
    "los conejos / lhya'aw nyewa": [-116.6804, 32.9555],
    "los terrinitos": [-116.6332, 32.8369],
    "los tules": [-116.6195, 33.2821],
    "lyons valley": [-116.7527, 32.7036],
    "mal\u00e1ava (janat)": [-116.7672, 33.2271],
    "manzanita": [-116.2955, 32.6755],
    "mar vista": [-117.2332, 33.177],
    "matamo": [-116.8993, 32.7863],
    "mesa grande": [-116.7783, 33.1898],
    "mesa grande reservation": [-116.8075, 33.1185],
    "milguatay": [-116.3588, 32.65],
    "mission trails": [-117.0548, 32.8353],
    "mission trails regional park": [-117.0548, 32.8353],
    "moosa canyon": [-117.1855, 33.2841],
    "morettis junction": [-116.7044, 33.2018],
    "mount helix": [-116.979, 32.7671],
    "mount laguna": [-116.4263, 32.8686],
    "national city": [-117.0888, 32.6745],
    "oak grove": [-116.8057, 33.3995],
    "oceanside": [-117.3135, 33.2159],
    "ocotillo wells": [-116.1452, 33.1411],
    "old japatul": [-116.6889, 32.7531],
    "pacific beach": [-117.2357, 32.7976],
    "pala": [-117.0777, 33.3729],
    "pala mesa": [-117.1609, 33.3418],
    "palomar mountain": [-116.8674, 33.3237],
    "pange": [-117.5679, 33.4195],
    "pauma": [-117.0005, 33.3342],
    "pauma valley": [-117.0087, 33.2859],
    "phelps corner": [-116.8142, 32.727],
    "pine hills": [-116.6249, 33.041],
    "pine valley": [-116.527, 32.8267],
    "potrero": [-116.6205, 32.6255],
    "poway": [-117.0379, 32.9782],
    "pueblo siding": [-116.3608, 32.6121],
    "pumual": [-117.1487, 33.27],
    "puyalamo": [-117.245, 33.329],
    "rainbow": [-117.1449, 33.4082],
    "ramona": [-116.8671, 33.0434],
    "ranchita": [-116.5221, 33.2193],
    "rancho bernardo": [-117.0723, 33.0198],
    "rancho cielo": [-117.145, 33.0568],
    "rancho san diego": [-116.932, 32.7475],
    "rancho santa fe": [-117.2091, 33.0261],
    "ridgecrest estates": [-117.2082, 33.3909],
    "rincon": [-116.9586, 33.2874],
    "rock springs": [-117.1141, 33.1441],
    "rosemont": [-116.9398, 33.0149],
    "san carlos": [-117.03, 32.798],
    "san diego": [-117.1347, 32.7949],
    "san diego airport": [-117.1933, 32.7338],
    "san diego country estates": [-116.8029, 33.0104],
    "san felipe": [-116.6117, 33.1943],
    "san luis rey heights": [-117.2092, 33.32],
    "san marcos": [-117.1746, 33.1377],
    "san onofre": [-117.5596, 33.3913],
    "santa fe creek": [-117.1872, 33.053],
    "santa fe hills": [-117.1663, 33.0205],
    "santa fe valley": [-117.1552, 33.0324],
    "santa ysabel": [-116.6793, 33.1101],
    "santee": [-116.9893, 32.8474],
    "scripps ranch": [-117.104, 32.914],
    "shady dell": [-116.9256, 32.9758],
    "shelter valley": [-116.4357, 33.0797],
    "snyaawkwatun": [-116.2912, 32.772],
    "solana beach": [-117.2604, 32.9942],
    "spring valley": [-116.9709, 32.7276],
    "stallion oaks": [-116.6357, 32.8793],
    "sun valley": [-117.2282, 32.9959],
    "sycuan": [-116.8322, 32.7927],
    "tecate": [-116.6292, 32.5851],
    "tierra del sol": [-116.3241, 32.6235],
    "tierrasanta": [-117.0905, 32.824],
    "twin oaks valley": [-117.176, 33.1974],
    "vallecito": [-116.4082, 32.9637],
    "valley center": [-117.0294, 33.2287],
    "viejas": [-116.6954, 32.8476],
    "vista": [-117.2426, 33.1949],
    "vista grande hills": [-116.9191, 32.7669],
    "warner springs": [-116.6378, 33.2816],
    "whispering pines": [-116.5912, 33.0895],
    "wil\u00e1kalpa": [-116.5619, 33.2464],
    "winter gardens": [-116.9328, 32.8259],
    "winterwarm": [-117.2189, 33.3526],
    "wynola": [-116.6467, 33.0918],
    "yapicha": [-116.8773, 33.2861],
    "yuima": [-116.9407, 33.308]
    /* GAZETTEER:END */
  };

  // Qualifier words, in TWO levels, because they are not equally safe to remove.
  //
  // ⚠️ LEVEL 2 CONTAINS "colorado", WHICH IS ALSO HALF OF "COLORADO SPRINGS". Removing it too
  // eagerly turns "downtown Colorado Springs" into "springs", which is ambiguous against
  // Steamboat and Glenwood, so the state's second-largest city stops resolving. Each level is
  // therefore tried in turn, and an exact match always wins over any further stripping.
  var POSITIONAL = /\b(downtown|the|area|city|of|in|near|around|greater|metro)\b/g;  // level 1
  var STATE = /\b(california|ca|usa|us|county|san diego county)\b/g;                                            // level 2

  /** Light normalize: case, punctuation, whitespace. Nothing removed. */
  function normalize(place) {
    return String(place == null ? "" : place)
      .toLowerCase().replace(/[.,]/g, " ").replace(/\s+/g, " ").trim();
  }

  function squeeze(k) { return k.replace(/\s+/g, " ").trim(); }

  /** The progressively stripped forms of a name, most literal first. */
  function forms(raw) {
    var lvl1 = squeeze(raw.replace(POSITIONAL, " "));
    var lvl2 = squeeze(lvl1.replace(STATE, " "));
    var out = [raw];
    if (lvl1 && out.indexOf(lvl1) === -1) out.push(lvl1);
    if (lvl2 && out.indexOf(lvl2) === -1) out.push(lvl2);
    return out;
  }

  /** Kept for callers that only want the aggressive form. */
  function stripNoise(key) {
    return squeeze(squeeze(key.replace(POSITIONAL, " ")).replace(STATE, " "));
  }

  /**
   * Word-sequence containment, so a match has to align to whole words.
   * Substring matching alone accepts nonsense: "ver" would match "denver", and "the" matched
   * "garden of the gods" as the single hit and resolved to it.
   */
  function containsWords(hay, needle) {
    var h = hay.split(" "), n = needle.split(" ");
    if (!n.length || n.length > h.length) return false;
    for (var i = 0; i + n.length <= h.length; i++) {
      var all = true;
      for (var j = 0; j < n.length; j++) { if (h[i + j] !== n[j]) { all = false; break; } }
      if (all) return true;
    }
    return false;
  }

  /**
   * Resolve a place name to { ok, center } or { ok:false, error }.
   * Exact match first, then a unique substring match. An AMBIGUOUS substring is rejected rather
   * than guessed: silently picking one of several places puts the answer somewhere the user did
   * not ask about, and the rest of the pipeline has no way to notice.
   */
  function geocode(place) {
    var raw = normalize(place);
    if (!raw) return { ok: false, error: "no place given" };
    var hit = function (k) {
      return { ok: true, name: k, center: { lon: PLACES[k][0], lat: PLACES[k][1] } };
    };

    // A query made only of qualifiers carries no location at all. Without this, "the" reaches
    // substring matching, hits "garden of the gods" as its only candidate, and resolves to it:
    // a confident point for a question that named no place.
    if (!stripNoise(raw)) {
      return { ok: false, error: "no place given (that is only a qualifier, not a place name)" };
    }

    var candidates = forms(raw);
    // Exact match at ANY strip level wins outright, before substring matching is considered.
    for (var i = 0; i < candidates.length; i++) {
      if (has(candidates[i])) return hit(candidates[i]);
    }

    var ambiguous = null;
    for (var j = 0; j < candidates.length; j++) {
      var key = candidates[j];
      if (!key) continue;
      var hits = Object.keys(PLACES).filter(function (k) {
        return containsWords(k, key) || containsWords(key, k);
      });
      if (hits.length > 1) {
        var starts = hits.filter(function (k) {
          return key.indexOf(k) === 0 || k.indexOf(key) === 0;
        });
        if (starts.length === 1) hits = starts;
      }
      if (hits.length === 1) return hit(hits[0]);
      // Remember the first ambiguity, but keep trying the stripped forms: a later form may
      // resolve cleanly, and only if none does is ambiguity the answer.
      if (hits.length > 1 && !ambiguous) ambiguous = hits;
    }

    if (ambiguous) {
      return { ok: false, ambiguous: ambiguous.slice(0, 8),
               error: "\"" + place + "\" matches several places: " +
                      ambiguous.slice(0, 8).join(", ") + ". Ask for one of those." };
    }
    return { ok: false,
             error: "\"" + place + "\" is not in the San Diego gazetteer. This map carries " +
                    "San Diego County data only, so places outside the county cannot be answered." };
  }

  var NEED_CENTRE = "query_properties needs a San Diego County place name (place), or BOTH lon and lat.";

  /**
   * The query centre from query_properties' arguments. The model may pass a place name, a
   * lon/lat pair, or both.
   *
   * ⚠️ EXPLICIT COORDINATES ALWAYS WIN. The gazetteer fills the centre only when NEITHER lon nor
   * lat is given. A place plus a lone lon or lat is an INCOMPLETE centre and is refused, never
   * completed or overwritten from the gazetteer: mixing one explicit axis with one geocoded axis
   * would put the query at a point nobody asked for, and the answer would still look right.
   *
   * Returns { ok:true, lon, lat, label, source:"coordinates"|"place" } or { ok:false, error }.
   * `label` is the caller's place_label, else the gazetteer name for a geocoded centre. A place
   * name is NOT used to label explicit coordinates, because they need not be that place.
   */
  function resolveCentre(args) {
    var a = args || {};
    var hasLon = a.lon != null, hasLat = a.lat != null;
    if (hasLon && hasLat) {
      return { ok: true, lon: a.lon, lat: a.lat, label: a.place_label || null,
               source: "coordinates" };
    }
    if (hasLon || hasLat) return { ok: false, error: NEED_CENTRE };
    if (a.place) {
      var g = geocode(a.place);
      if (!g.ok) return { ok: false, error: g.error };
      return { ok: true, lon: g.center.lon, lat: g.center.lat, label: a.place_label || g.name,
               source: "place" };
    }
    return { ok: false, error: NEED_CENTRE };
  }

  return { PLACES: PLACES, has: has, normalize: normalize, forms: forms, stripNoise: stripNoise,
           containsWords: containsWords, geocode: geocode, resolveCentre: resolveCentre };
});
