/**
 * Colorado-only gazetteer for the copilot's `geocode` tool.
 *
 * ⚠️ COLORADO ONLY, DELIBERATELY. This app carries Colorado data and nothing else, so a place
 * outside the state is a question the extract cannot answer. Returning a point anyway would put
 * a marker where there is no data and read as "no risk here", which is the opposite of the
 * truth. Unknown places are REJECTED with the list of what is known, not approximated.
 *
 * Coordinates are city centres (the US Census place centroid, rounded to 4 decimals, roughly
 * 10 m), plus a few landmarks people actually ask about. "downtown <city>" resolves to the
 * city centre, which is what the phrase means at a 10-mile radius.
 *
 * The real fix for free-form places is an Overture places extract queried through the same
 * engine. This list exists so v1 can answer the questions people actually ask without that.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else (root.CoRiskQuery = root.CoRiskQuery || {}).gazetteer = factory();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  /**
   * ⚠️ EVERY LOOKUP USES has(), NEVER A BARE `PLACES[key]`.
   *
   * A plain object inherits `constructor`, `__proto__` and friends from Object.prototype, so
   * `PLACES["constructor"]` is truthy and the lookup "succeeds" with a value that is not a
   * place. geocode("constructor") returned `{ok:true, center:{}}`: the tool told the copilot the
   * place resolved and handed it an empty centre. A confident wrong answer, which is exactly
   * what this file's unknown-place rejection exists to prevent.
   *
   * Only lower-cased keys reach here (normalize() lower-cases), which is why `toString` and
   * `hasOwnProperty` happened not to collide while `constructor` and `__proto__` did. That is
   * luck, not a design, so the guard is on the lookup rather than on the spelling.
   */
  function has(key) { return Object.prototype.hasOwnProperty.call(PLACES, key); }

  // City of San Diego: neighbourhoods from the app's places.json (Overture divisions), plus
  // landmarks people name. Generated by part2_map_app/data/build_app_data.py; edit that, not
  // this list.
  var PLACES = {
    /* GAZETTEER:BEGIN */
    "allied gardens": [-117.0811, 32.795],
    "balboa park": [-117.1466, 32.7341],
    "banker's hill": [-117.162, 32.7283],
    "barrio logan": [-117.1387, 32.6969],
    "bay terraces": [-117.0381, 32.6902],
    "black mountain ranch": [-117.1414, 33.0041],
    "carmel mountain ranch": [-117.0817, 32.984],
    "carmel valley": [-117.2135, 32.9454],
    "carroll canyon": [-117.1532, 32.9028],
    "city heights": [-117.0972, 32.7457],
    "clairemont": [-117.1905, 32.8225],
    "del cerro": [-117.07, 32.788],
    "del mar heights": [-117.2437, 32.9523],
    "downtown san diego": [-117.1625, 32.7157],
    "encanto": [-117.0724, 32.7111],
    "golden hill": [-117.1302, 32.7192],
    "grantville": [-117.0986, 32.7871],
    "hillcrest": [-117.1574, 32.7482],
    "kearny mesa": [-117.1461, 32.8285],
    "la jolla": [-117.2713, 32.8328],
    "linda vista": [-117.1724, 32.7896],
    "logan heights": [-117.117, 32.7003],
    "mid-city": [-117.0665, 32.7582],
    "middletown": [-117.1739, 32.7396],
    "midway district": [-117.217, 32.7466],
    "mira mesa": [-117.1422, 32.9198],
    "miramar": [-117.1403, 32.8863],
    "mission beach": [-117.2483, 32.7802],
    "mission hills": [-117.1821, 32.7517],
    "mission trails": [-117.0548, 32.8353],
    "mission trails regional park": [-117.0548, 32.8353],
    "mission valley": [-117.1503, 32.7687],
    "morena": [-117.1971, 32.7789],
    "navajo": [-117.0579, 32.8062],
    "normal heights": [-117.1172, 32.7639],
    "north park": [-117.1303, 32.7462],
    "ocean beach": [-117.2428, 32.7452],
    "old town": [-117.1952, 32.7535],
    "otay mesa": [-116.9837, 32.5681],
    "pacific beach": [-117.2357, 32.7976],
    "pacific highlands ranch": [-117.1943, 32.9652],
    "paradise hills": [-117.0579, 32.6781],
    "point loma": [-117.2396, 32.7238],
    "rancho bernardo": [-117.0723, 33.0198],
    "rancho encantada": [-117.0353, 32.9249],
    "rancho pe\u00f1asquitos": [-117.1289, 32.9587],
    "sabre springs": [-117.0902, 32.9441],
    "san carlos": [-117.03, 32.798],
    "san diego airport": [-117.1933, 32.7338],
    "san pasqual valley": [-116.9955, 33.0943],
    "san ysidro": [-117.0431, 32.5664],
    "scripps ranch": [-117.104, 32.914],
    "serra mesa": [-117.1388, 32.7986],
    "skyline": [-117.0326, 32.7077],
    "sorrento mesa": [-117.1841, 32.9057],
    "sorrento valley": [-117.2153, 32.8926],
    "south san diego": [-117.0777, 32.5768],
    "tierrasanta": [-117.0905, 32.824],
    "tijuana river valley": [-117.0802, 32.556],
    "torrey highlands": [-117.1556, 32.9612],
    "torrey hills": [-117.2218, 32.921],
    "torrey pines": [-117.2418, 32.8816],
    "university city": [-117.2154, 32.8547]
    /* GAZETTEER:END */
  };

  // Qualifier words, in TWO levels, because they are not equally safe to remove.
  //
  // ⚠️ LEVEL 2 CONTAINS "colorado", WHICH IS ALSO HALF OF "COLORADO SPRINGS". Removing it too
  // eagerly turns "downtown Colorado Springs" into "springs", which is ambiguous against
  // Steamboat and Glenwood, so the state's second-largest city stops resolving. Each level is
  // therefore tried in turn, and an exact match always wins over any further stripping.
  var POSITIONAL = /\b(downtown|the|area|city|of|in|near|around|greater|metro)\b/g;  // level 1
  var STATE = /\b(california|ca|usa|us|san diego county|county|san diego)\b/g;                                            // level 2

  /** Light normalize: case, punctuation, whitespace. Nothing removed. */
  function normalize(place) {
    return String(place == null ? "" : place)
      .toLowerCase().replace(/[.,]/g, " ").replace(/\s+/g, " ").trim();
  }

  function squeeze(k) { return k.replace(/\s+/g, " ").trim(); }

  /** The progressively stripped forms of a name, most literal first. */
  function forms(raw) {
    var lvl1 = squeeze(raw.replace(POSITIONAL, " "));
    var lvl2 = squeeze(lvl1.replace(STATE, " "));
    var out = [raw];
    if (lvl1 && out.indexOf(lvl1) === -1) out.push(lvl1);
    if (lvl2 && out.indexOf(lvl2) === -1) out.push(lvl2);
    return out;
  }

  /** Kept for callers that only want the aggressive form. */
  function stripNoise(key) {
    return squeeze(squeeze(key.replace(POSITIONAL, " ")).replace(STATE, " "));
  }

  /**
   * Word-sequence containment, so a match has to align to whole words.
   * Substring matching alone accepts nonsense: "ver" would match "denver", and "the" matched
   * "garden of the gods" as the single hit and resolved to it.
   */
  function containsWords(hay, needle) {
    var h = hay.split(" "), n = needle.split(" ");
    if (!n.length || n.length > h.length) return false;
    for (var i = 0; i + n.length <= h.length; i++) {
      var all = true;
      for (var j = 0; j < n.length; j++) { if (h[i + j] !== n[j]) { all = false; break; } }
      if (all) return true;
    }
    return false;
  }

  /**
   * Resolve a place name to { ok, center } or { ok:false, error }.
   * Exact match first, then a unique substring match. An AMBIGUOUS substring is rejected rather
   * than guessed: silently picking one of several places puts the answer somewhere the user did
   * not ask about, and the rest of the pipeline has no way to notice.
   */
  function geocode(place) {
    var raw = normalize(place);
    if (!raw) return { ok: false, error: "no place given" };
    var hit = function (k) {
      return { ok: true, name: k, center: { lon: PLACES[k][0], lat: PLACES[k][1] } };
    };

    // A query made only of qualifiers carries no location at all. Without this, "the" reaches
    // substring matching, hits "garden of the gods" as its only candidate, and resolves to it:
    // a confident point for a question that named no place.
    if (!stripNoise(raw)) {
      return { ok: false, error: "no place given (that is only a qualifier, not a place name)" };
    }

    var candidates = forms(raw);
    // Exact match at ANY strip level wins outright, before substring matching is considered.
    for (var i = 0; i < candidates.length; i++) {
      if (has(candidates[i])) return hit(candidates[i]);
    }

    var ambiguous = null;
    for (var j = 0; j < candidates.length; j++) {
      var key = candidates[j];
      if (!key) continue;
      var hits = Object.keys(PLACES).filter(function (k) {
        return containsWords(k, key) || containsWords(key, k);
      });
      if (hits.length > 1) {
        var starts = hits.filter(function (k) {
          return key.indexOf(k) === 0 || k.indexOf(key) === 0;
        });
        if (starts.length === 1) hits = starts;
      }
      if (hits.length === 1) return hit(hits[0]);
      // Remember the first ambiguity, but keep trying the stripped forms: a later form may
      // resolve cleanly, and only if none does is ambiguity the answer.
      if (hits.length > 1 && !ambiguous) ambiguous = hits;
    }

    if (ambiguous) {
      return { ok: false, ambiguous: ambiguous.slice(0, 8),
               error: "\"" + place + "\" matches several places: " +
                      ambiguous.slice(0, 8).join(", ") + ". Ask for one of those." };
    }
    return { ok: false,
             error: "\"" + place + "\" is not in the San Diego gazetteer. This map carries " +
                    "San Diego County data only, so places outside the county cannot be answered." };
  }

  var NEED_CENTRE = "query_properties needs a City of San Diego place name (place), or BOTH lon and lat.";

  /**
   * The query centre from query_properties' arguments. The model may pass a place name, a
   * lon/lat pair, or both.
   *
   * ⚠️ EXPLICIT COORDINATES ALWAYS WIN. The gazetteer fills the centre only when NEITHER lon nor
   * lat is given. A place plus a lone lon or lat is an INCOMPLETE centre and is refused, never
   * completed or overwritten from the gazetteer: mixing one explicit axis with one geocoded axis
   * would put the query at a point nobody asked for, and the answer would still look right.
   *
   * Returns { ok:true, lon, lat, label, source:"coordinates"|"place" } or { ok:false, error }.
   * `label` is the caller's place_label, else the gazetteer name for a geocoded centre. A place
   * name is NOT used to label explicit coordinates, because they need not be that place.
   */
  function resolveCentre(args) {
    var a = args || {};
    var hasLon = a.lon != null, hasLat = a.lat != null;
    if (hasLon && hasLat) {
      return { ok: true, lon: a.lon, lat: a.lat, label: a.place_label || null,
               source: "coordinates" };
    }
    if (hasLon || hasLat) return { ok: false, error: NEED_CENTRE };
    if (a.place) {
      var g = geocode(a.place);
      if (!g.ok) return { ok: false, error: g.error };
      return { ok: true, lon: g.center.lon, lat: g.center.lat, label: a.place_label || g.name,
               source: "place" };
    }
    return { ok: false, error: NEED_CENTRE };
  }

  return { PLACES: PLACES, has: has, normalize: normalize, forms: forms, stripNoise: stripNoise,
           containsWords: containsWords, geocode: geocode, resolveCentre: resolveCentre };
});
