/**
 * SQL construction for "ask the data", including the file-to-relation substitution.
 *
 * Phase 3 of ASK_THE_DATA_PLAN.md (section 3). The model NEVER emits SQL. It fills typed
 * arguments; this file builds the statement from a fixed template plus validated values.
 *
 * THE SUBSTITUTION RULE, EXACTLY (this is the part that is easy to get subtly wrong):
 *   - the engine registers each selected county part file under its own name,
 *     `co_risk_query_<fips>`;
 *   - the template is written against ONE relation, `co_risk_query`, and keeps its own alias:
 *     `FROM co_risk_query b`;
 *   - substitution replaces the IDENTIFIER `co_risk_query` only, with a parenthesised derived
 *     table, and the derived table carries NO ALIAS OF ITS OWN:
 *       FROM co_risk_query b
 *         -> FROM (SELECT * FROM co_risk_query_08001 UNION ALL SELECT * FROM co_risk_query_08031) b
 *
 * ⚠️ IF THE DERIVED TABLE CARRIED ITS OWN `AS b`, the result would be `... ) AS b b` -- two
 * aliases on one relation, a syntax error at best and a confusing one, since the template that
 * produced it looks correct in isolation. The alias belongs to the CALLER, always.
 *
 * ⚠️ THE NAME BOUNDARY MATTERS. `co_risk_query_08001` must not be rewritten into
 * `(SELECT ...)_08001`. A word-boundary match handles this for free -- there is no word boundary
 * between `query` and `_08001`, because `_` is a word character -- but it is the kind of thing a
 * later "simplification" to a plain string replace would break silently, which is why the tests
 * assert it directly.
 *
 * NO DDL. The plan does not assume the engine supports CREATE VIEW, and nothing here needs it:
 * a derived table in the FROM clause is plain SQL that any DataFusion-based engine parses.
 *
 * TIE-BREAKS ARE PART OF THE CONTRACT, NOT A DETAIL. Every ordering ends with
 * `building_id ASC`, so tied scores resolve deterministically and a shared versioned link
 * reproduces the same ten rows and the same ten markers, not a different ten of equal score.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else (root.CoRiskQuery = root.CoRiskQuery || {}).sqlbuild = factory();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  var RELATION = "co_risk_query";

  /**
   * How the geometry column is read back.
   *
   * ⚠️ THE ENGINE DOES NOT READ GeoParquet METADATA, so `geom_5070` arrives as a plain binary
   * column and every spatial kernel refuses it ("No kernel matching arguments"). It has to be
   * decoded from WKB at read time. The SRID then has to be set explicitly as well: the engine
   * compares CRS before it compares geometry, and a decoded WKB has none, which fails against
   * the query point's EPSG:5070 with "Mismatched CRS arguments: None vs epsg:5070". Both were
   * measured against @cereusdb/standard, not assumed.
   */
  var GEOM = "ST_SetSRID(ST_GeomFromWKB(b.geom_5070), 5070)";

  /**
   * EPSG:5070 is NAD83 / Conus Albers, which is EQUAL-AREA, not equidistant. Measured against
   * geodesic distance across Colorado, a planar distance in it runs about +0.7% to +0.8%
   * north-south and -0.6% to -0.7% east-west. So `ST_DWithin(..., 16093.4)` is not a 10-mile
   * circle on the ground; north-south it falls about 123 m SHORT.
   *
   * Falling short is the dangerous direction: it drops buildings that really are inside the
   * radius, with no error anywhere, which is the silent undercount the floors guardrail exists
   * to prevent. So the predicate is inflated past the worst measured distortion, making the SQL
   * filter a conservative SUPERSET in every direction, and the executor then applies the exact
   * radius using a true geodesic distance computed from the returned lon/lat.
   *
   * There is no ST_DistanceSpheroid in this build, so the projection cannot be avoided in SQL.
   */
  var PLANAR_SLACK = 1.01;
  var RELATION_RE = /\bco_risk_query\b/g;
  // Relation names are version-scoped (co_risk_query_v<YYYYMMDD>_<FIPS>), so a newly published
  // extract cannot reuse a cached registration of the previous one.
  var TABLE_RE = /^co_risk_query_v\d{8}_\d{5}$/;

  // Re-stated here rather than imported so that a build path which somehow skipped validation
  // still cannot reach an ORDER BY with a free string. Defence in depth: validate.js is the
  // gate, this is the lock on the door behind it.
  var METRIC_COLUMNS = ["composite", "wf_score", "hail_score", "flood_score", "wind_score",
                        "access_score"];

  /** The derived table that stands in for the registered per-county files. No alias; see above. */
  function derivedTable(tables) {
    if (!tables || !tables.length) {
      throw new Error("no county part files selected - nothing to query");
    }
    tables.forEach(function (t) {
      // The table names are generated by registry.js from manifest FIPS values, never typed by
      // a user or a model. Checking the shape anyway keeps that true if a caller ever changes.
      if (!TABLE_RE.test(t)) throw new Error("refusing to build SQL for table name: " + t);
    });
    return "(" + tables.map(function (t) { return "SELECT * FROM " + t; }).join(" UNION ALL ") + ")";
  }

  /** Substitute the identifier `co_risk_query` and nothing else. */
  function substituteRelation(sql, tables) {
    if (!RELATION_RE.test(sql)) {
      RELATION_RE.lastIndex = 0;
      throw new Error("template does not reference " + RELATION + " - substitution would be a no-op");
    }
    RELATION_RE.lastIndex = 0;
    return sql.replace(RELATION_RE, derivedTable(tables));
  }

  function num(n) {
    if (typeof n !== "number" || !isFinite(n)) throw new Error("non-finite number in SQL build");
    return String(n);
  }

  /**
   * The top-N-within-radius template, before substitution. Written against `co_risk_query` so it
   * reads the way the plan's worked example reads, and so the substitution has exactly one job.
   *
   * CRS: the centre is transformed INTO EPSG:5070 and compared against the stored 5070 geometry,
   * so `ST_DWithin(..., 16093.4)` is 16,093.4 METRES. The same geometry is transformed BACK to
   * 4326 for lon/lat, because a MapLibre source needs WGS84. Doing the distance test in 4326
   * would compare degrees and quietly return most of the state.
   *
   * The `h3_<res> IN (...)` prefilter is what the Parquet reader prunes on. It is omitted
   * entirely on the county-fallback path, where the bounded read comes from registering only the
   * intersecting counties.
   */
  /**
   * How many rows the SQL asks for, given the caller's limit.
   *
   * Exported because the executor needs THIS number to know whether a short answer means "there
   * are only that many" or "the over-fetch ran out". Comparing against a hardcoded guess is how
   * that notice ends up unable to fire.
   */
  function fetchLimitFor(limit) { return Math.min(MAX_FETCH, limit * 2 + 20); }

  var MAX_FETCH = 200;

  function template(opts) {
    var metric = opts.metricColumn;
    if (METRIC_COLUMNS.indexOf(metric) === -1) throw new Error("metric not allowlisted: " + metric);

    var prefilter = "";
    if (opts.cover && opts.cover.mode === "h3") {
      var ids = opts.cover.cellIds;
      if (!ids || !ids.length) throw new Error("h3 prefilter requested with no cells");
      ids.forEach(function (id) {
        if (!/^\d+$/.test(String(id))) throw new Error("non-numeric H3 cell id: " + id);
      });
      // Qualified with the caller's alias: the FROM clause also carries `pt`, and an
      // unqualified column that later exists on both sides is an ambiguous-reference failure
      // that only shows up once someone adds a column to the other relation.
      prefilter = "b." + opts.cover.column + " IN (" + ids.join(", ") + ")\n" +
                  "  AND ";
    }

    // Over-fetch so the executor's exact geodesic filter still has `limit` rows to return after
    // it removes the slack ring. The ring is ~2% of the disk area, so this margin is ample; the
    // executor reports it honestly if a query ever exhausts it.
    var fetchLimit = fetchLimitFor(opts.limit);

    return "" +
      "WITH pt AS (\n" +
      "  SELECT ST_Transform(ST_Point(" + num(opts.center.lon) + ", " + num(opts.center.lat) +
      "), 'EPSG:4326', 'EPSG:5070') AS g\n" +
      ")\n" +
      "SELECT b.building_id, b.composite, b.wf_score, b.hail_score, b.flood_score,\n" +
      "       b.wind_score, b.access_score, b.county,\n" +
      "       ST_X(ST_Transform(" + GEOM + ", 'EPSG:5070', 'EPSG:4326')) AS lon,\n" +
      "       ST_Y(ST_Transform(" + GEOM + ", 'EPSG:5070', 'EPSG:4326')) AS lat,\n" +
      "       ST_Distance(" + GEOM + ", pt.g) AS planar_dist_m\n" +
      "FROM " + RELATION + " b, pt\n" +
      "WHERE " + prefilter + "ST_DWithin(" + GEOM + ", pt.g, " +
      num(Math.round(opts.radius_m * PLANAR_SLACK * 10) / 10) + ")\n" +
      "ORDER BY b." + metric + " DESC, b.building_id ASC\n" +
      "LIMIT " + num(fetchLimit) + ";";
  }

  /**
   * The one call the executor makes. Takes a VALIDATED query value, the cover decision and the
   * selected county descriptors; returns the statement the worker runs plus the per-file
   * registrations it needs first.
   */
  function buildQuery(value, cover, counties) {
    var tables = counties.map(function (c) { return c.table; });
    var sql = substituteRelation(template({
      center: value.center,
      radius_m: value.radius_m,
      limit: value.limit,
      metricColumn: value.metricColumn,
      cover: cover
    }), tables);
    return {
      sql: sql,
      fetchLimit: fetchLimitFor(value.limit),
      registrations: counties.map(function (c) { return { url: c.url, table: c.table }; }),
      prune: cover.mode === "h3"
        ? { mode: "h3", column: cover.column, cells: cover.cellCount }
        : { mode: "county", counties: counties.length }
    };
  }

  return {
    RELATION: RELATION,
    GEOM: GEOM,
    PLANAR_SLACK: PLANAR_SLACK,
    MAX_FETCH: MAX_FETCH,
    fetchLimitFor: fetchLimitFor,
    METRIC_COLUMNS: METRIC_COLUMNS,
    derivedTable: derivedTable,
    substituteRelation: substituteRelation,
    template: template,
    buildQuery: buildQuery
  };
});
